apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: registryweb-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registryweb
  template:
    metadata:
      labels:
        app: registryweb
    spec:
      containers:
      - env:
        - name: REGISTRY_URL
          value: https://192.168.1.171:50000/v2
        - name: REGISTRY_TRUST_ANY_SSL
          value: 'true'
        - name: REGISTRY_NAME
          value: daed.duckdns.org:50000
        - name: REGISTRY_BASIC_AUTH
          value: ZG9ja2VydXNlcjp3SEdNd3FWS3pMQTQ=
        image: hyper/docker-registry-web
        name: registryweb
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: registryweb
  name: registryweb
  namespace: default
spec:
  ports:
  - nodePort: 30880
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: registryweb
  type: NodePort
