apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: taisapp-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taisapp
  template:
    metadata:
      labels:
        app: taisapp
    spec:
      containers:
      - env:
        image: daed.duckdns.org:50000/tais-app:4
        name: taisapp
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: taisapp
  name: taisapp
  namespace: default
spec:
  ports:
  - nodePort: 35000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: taisapp
  type: NodePort
