apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: uptimekuma-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
      - env:
        image: louislam/uptime-kuma:1
        name: uptimekuma
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: uptimekuma
  name: uptimekuma
  namespace: default
spec:
  ports:
  - nodePort: 30001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: uptimekuma
  type: NodePort
